### ISSUE TITLE
Attempting to use uninitialized value input_producer/limit_epochs/epochs

### ISSUE THREAD

**Issue by Dan1900** [OlavHN/fast-neural-style#2]
Thank you for share your code. I tried to train my own model, but I got this error,Attempting to use uninitialized value input_producer/limit_epochs/epochs. I run it with python2.7, whether it is the reason?

**Comment by ycjing** [comment]
I run it with python3.5 but I got the same error as well. Does anyone has any ideas? Thanks!

**Comment by OlavHN** [comment]
Try the fork in https://github.com/bazarevsky/fast-neural-style which seems to fix that issue.

See issue #4 for details.

I'll keep this issue open till I've commited a fix.

**Comment by ycjing** [comment]
@OlavHN Thanks!

**Comment by MycChiu** [comment]
If the above fix didn't work, and you are using newer version of Tensorflow, you need to initialize with 
`sess.run(initialize_local_variables())`
before you start the queue runners. [reasons explained here](https://github.com/tensorflow/tensorflow/issues/1045#issuecomment-239789244)

**Comment by ycjing** [comment]
MycChiu is right. When you train your own model, the fork in https://github.com/bazarevsky/fast-neural-style will still report an error and sess.run(initialize_local_variables()) solves it perfectly. BTW, personally, if the code of training process and the generating process are separated into two files like https://github.com/yusuketomoto/chainer-fast-neuralstyle, the code may be clearer. Maybe I'll pull a request.

**Comment by Dan1900** [comment]
MycChiu is right!
