### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by lengstrom** [OlavHN/fast-neural-style#3]
Looks like https://github.com/OlavHN/fast-neural-style/blob/master/vgg.py is directly copied from https://github.com/anishathalye/neural-style - maybe you forgot to attribute that (as required by GPL?)

**Comment by OlavHN** [comment]
You are absolutely right.

The anishathalye/neural-style repo was acknowledged in the readme file, but I should have been more explicit. Updated both the readme and vgg.py -file. Thanks for filing!
