### ISSUE TITLE
How long is the training process?

### ISSUE THREAD

**Issue by ycjing** [OlavHN/fast-neural-style#5]
Thanks for the great code. When I run the model of my own style, I found the training process is quite time-consuming. It almost takes one day for one style on my Quadro K4200. I want to compare the training time on different GPUs. Could anyone who had run the code share your training time? Thanks ahead of time! (Batch size is set to 2)

**Comment by Dan1900** [comment]
I trained on titan x ,the batch size is set to 1, and it costs about 0.5 minute for 100 iterations.

**Comment by ycjing** [comment]
@Dan1900 Thanks!
