### ISSUE TITLE
About the batch training problem

### ISSUE THREAD

**Issue by Dan1900** [OlavHN/fast-neural-style#7]
I changed this line:
          # style_loss += tf.nn.l2_loss(tf.reduce_sum(gram(generated_images) - style_image, 0)) / tf.to_float(size)
            style_loss += tf.nn.l2_loss(gram(generated_images) - style_image) / tf.to_float(size)
and it worked. Is it the right way?

**Comment by OlavHN** [comment]
Not totoally sure.

Now using `style_loss += tf.nn.l2_loss(gram(generated_images) - style_gram) / tf.to_float(size)`

and relying on style_gram to be broadcasted over the batch dimention. Think that will work.
