### ISSUE TITLE
Get 'size' must be a 1-D Tensor of 2 elements: new_height, new_width error

### ISSUE THREAD

**Issue by Funkwai** [OlavHN/fast-neural-style#9]
**I using the following command to train the model on 1080**
$ python3 fast_neural_style.py --TRAIN_IMAGES_PATH ../../tar/train2014 --MODEL_PATH models/model-1015-2000 --STYLE_IMAGES star_night.jpg --BATCH_SIZE 4
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcurand.so.8.0 locally

**but get the error :**
Traceback (most recent call last):
  File "fast_neural_style.py", line 188, in <module>
    tf.app.run()
  File "/home/dl/tensorflow/_python_build/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "fast_neural_style.py", line 114, in main
    style_features_t = get_style_features(style_paths, style_layers)
  File "fast_neural_style.py", line 53, in get_style_features
    images = tf.pack([reader.get_image(path, size) for path in style_paths])
  File "fast_neural_style.py", line 53, in <listcomp>
    images = tf.pack([reader.get_image(path, size) for path in style_paths])
  File "/home/dl/src/fast-neural-style/reader.py", line 30, in get_image
    return preprocess(image, size, max_length)
  File "/home/dl/src/fast-neural-style/reader.py", line 21, in preprocess
    resized_image = tf.image.resize_images(image, tf.to_int32(new_height), tf.to_int32(new_width))
  File "/home/dl/tensorflow/_python_build/tensorflow/python/ops/image_ops.py", line 784, in resize_images
    raise ValueError('\'size\' must be a 1-D Tensor of 2 elements: '
**ValueError: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width**

Do you guy know how to solve it ? thanks~~

**Comment by Funkwai** [comment]
Solved, due to I am using Tensorflow r0.11 version, and the API _**tf.image.resize_images**_ is changed.
so modify the reader.py as follow, it works.
`+ resized_image = tf.image.resize_images(image, size=[tf.to_int32(new_height), tf.to_int32(new_width)])`
`-  resized_image = tf.image.resize_images(image, tf.to_int32(new_height), tf.to_int32(new_width))`

**Comment by OlavHN** [comment]
Thanks for reporting!

Now passing size args as array.
